# Generated by Django 3.0.3 on 2020-03-30 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0004_auto_20200330_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=64),
        ),
    ]
