# Generated by Django 3.0.3 on 2020-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0007_auto_20200330_0055'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickName'], name='zzname'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='abc',
        ),
    ]
