# Generated by Django 3.0.3 on 2020-03-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juheapp', '0008_auto_20200330_0103'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='zzname',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['nickName'], name='nickname'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
